type TextStreamData {
  sessionId: String!
  data: AWSJSON!
}

type Message {
  message_id: String!
  session_id: String!
  message_content: String!
  student_sent: Boolean!
  time_sent: String!
}

type Mutation {
  publishTextStream(sessionId: String!, data: AWSJSON!): TextStreamData @aws_iam @aws_cognito_user_pools
}

type Subscription {
  onTextStream(sessionId: String!): TextStreamData
    @aws_subscribe(mutations: ["publishTextStream"]) @aws_iam @aws_cognito_user_pools
}

type Query {
  getTextStream: String
  listMessagesBySession(sessionId: String!): [Message] @aws_cognito_user_pools
}
