#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

OUTPUT_FILE="docs/tech-debt-scorecard.md"
INCIDENT_FILE="docs/ops/incidents.json"

ROUTER_TOTAL=$(find cdk/lambda/lib -maxdepth 2 -type f -name "router.js" | wc -l | tr -d ' ')
ROUTER_DUP_COUNT=$(find cdk/lambda/lib -maxdepth 2 -type f -name "router.js" -print0 | xargs -0 grep -El "queryStringParameters|queryStringParams" | wc -l | tr -d ' ')
CONSOLE_LOG_COUNT=$(grep -RhoE "console\.(log|warn|error)\(" cdk frontend/src 2>/dev/null | wc -l | tr -d ' ')

FRONTEND_TEST_FILES=$(find frontend/src -type f \( -name "*.test.js" -o -name "*.test.jsx" -o -name "*.spec.js" -o -name "*.spec.jsx" -o -name "*.test.ts" -o -name "*.test.tsx" -o -name "*.spec.ts" -o -name "*.spec.tsx" \) | wc -l | tr -d ' ')
CDK_TEST_FILES=$(find cdk -type f \( -name "*.test.ts" -o -name "*.spec.ts" -o -name "*.test.js" -o -name "*.spec.js" \) | wc -l | tr -d ' ')

if [ -f "$INCIDENT_FILE" ]; then
  ESCAPED_INCIDENTS=$(python3 - <<'PY'
import json
from pathlib import Path
p = Path("docs/ops/incidents.json")
items = json.loads(p.read_text(encoding="utf-8"))
print(sum(1 for i in items if i.get("escaped") is True))
PY
)
else
  ESCAPED_INCIDENTS="0"
fi

HOTSPOTS=$(find frontend/src -type f \( -name "*.js" -o -name "*.jsx" -o -name "*.ts" -o -name "*.tsx" \) -print0 \
  | xargs -0 wc -l \
  | grep -v " total$" \
  | sort -nr \
  | head -n 10)

GENERATED_AT=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

cat > "$OUTPUT_FILE" <<EOF
# Tech Debt Scorecard

Generated: $GENERATED_AT

This scorecard is generated by .github/scripts/generate_debt_scorecard.sh and acts as the Phase 0 baseline.

## Baseline metrics

| Metric | Baseline value | Notes |
| --- | ---: | --- |
| Route-handler duplication count | $ROUTER_DUP_COUNT / $ROUTER_TOTAL routers | Routers with inline ownership-guard style logic (queryStringParameters or queryStringParams) instead of a shared pipeline. |
| Raw console logging calls | $CONSOLE_LOG_COUNT | Count of console.log, console.warn, and console.error calls in cdk/ and frontend/src/. |
| Frontend file complexity hotspots | Top 10 by LOC | See hotspot table below. |
| Test coverage trend signal | cdk test files: $CDK_TEST_FILES; frontend test files: $FRONTEND_TEST_FILES | Frontend automated tests are currently sparse; use this as a trend indicator until unified coverage reporting is introduced. |
| Escaped production incidents | $ESCAPED_INCIDENTS | Sourced from docs/ops/incidents.json. |

## Frontend complexity hotspots (by lines of code)

\`\`\`text
$HOTSPOTS
\`\`\`

## How to refresh

Run:

\`\`\`bash
bash .github/scripts/generate_debt_scorecard.sh
\`\`\`
EOF

echo "Wrote $OUTPUT_FILE"
