$ErrorActionPreference = 'Stop'

$routerFiles = Get-ChildItem cdk/lambda/lib -Recurse -Filter router.js -File
$routerTotal = $routerFiles.Count
$routerDup = ($routerFiles | Where-Object { (Get-Content $_.FullName -Raw) -match 'queryStringParameters|queryStringParams' }).Count

$consoleTargets = @(
  Get-ChildItem cdk -Recurse -File -ErrorAction SilentlyContinue | Where-Object { $_.Extension -in '.js', '.jsx', '.ts', '.tsx', '.py' }
  Get-ChildItem frontend/src -Recurse -File -ErrorAction SilentlyContinue | Where-Object { $_.Extension -in '.js', '.jsx', '.ts', '.tsx' }
)
$consoleCount = 0
foreach ($target in $consoleTargets) {
  $matches = Select-String -Path $target.FullName -Pattern 'console\.(log|warn|error)\(' -AllMatches
  foreach ($match in $matches) {
    $consoleCount += $match.Matches.Count
  }
}

$frontendTests = (Get-ChildItem frontend/src -Recurse -File | Where-Object { $_.Name -match '\.(test|spec)\.(js|jsx|ts|tsx)$' }).Count
$cdkTests = (Get-ChildItem cdk -Recurse -File | Where-Object { $_.Name -match '\.(test|spec)\.(js|ts)$' }).Count

$incidents = Get-Content docs/ops/incidents.json -Raw | ConvertFrom-Json
$escaped = @($incidents | Where-Object { $_.escaped -eq $true }).Count

$hotspots = Get-ChildItem frontend/src -Recurse -File |
  Where-Object { $_.Extension -in '.js', '.jsx', '.ts', '.tsx' } |
  ForEach-Object {
    $lines = (Get-Content $_.FullName | Measure-Object -Line).Lines
    [PSCustomObject]@{
      Lines = $lines
      Path = ($_.FullName -replace [regex]::Escape((Get-Location).Path + '\\'), '').Replace('\\', '/')
    }
  } |
  Sort-Object Lines -Descending |
  Select-Object -First 10

$generated = (Get-Date).ToUniversalTime().ToString('yyyy-MM-dd HH:mm:ss UTC')
$hotspotText = ($hotspots | ForEach-Object { "{0,6} {1}" -f $_.Lines, $_.Path }) -join "`n"

$content = @"
# Tech Debt Scorecard

Generated: $generated

This scorecard is generated by .github/scripts/generate_debt_scorecard.sh and acts as the Phase 0 baseline.

## Baseline metrics

| Metric | Baseline value | Notes |
| --- | ---: | --- |
| Route-handler duplication count | $routerDup / $routerTotal routers | Routers with inline ownership-guard style logic (`queryStringParameters`) instead of a shared pipeline. |
| Raw console logging calls | $consoleCount | Count of `console.log`, `console.warn`, and `console.error` calls in `cdk/` and `frontend/src/`. |
| Frontend file complexity hotspots | Top 10 by LOC | See hotspot table below. |
| Test coverage trend signal | cdk test files: $cdkTests; frontend test files: $frontendTests | Frontend automated tests are currently sparse; use this as a trend indicator until unified coverage reporting is introduced. |
| Escaped production incidents | $escaped | Sourced from `docs/ops/incidents.json`. |

## Frontend complexity hotspots (by lines of code)

```text
$hotspotText
```

## How to refresh

Run:

```bash
bash .github/scripts/generate_debt_scorecard.sh
```
"@

Set-Content -Path docs/tech-debt-scorecard.md -Value $content -Encoding UTF8
Write-Host 'Wrote docs/tech-debt-scorecard.md'
