"""
rag_chain.py — LLaMA 3 70B + pgvector RAG for hybrid voice mode.

Uses the same helpers as text_generation so voice and text responses are
generated by the same model with the same knowledge base and the same
system prompt (loaded from DB with a hardcoded fallback).

Chain structure mirrors conversation.py get_response().
"""

import asyncio
import json
import logging
import os

import boto3
from langchain.chains import create_retrieval_chain
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain_aws import BedrockEmbeddings
from langchain_aws import ChatBedrock
from langchain_community.chat_message_histories import DynamoDBChatMessageHistory
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.runnables.history import RunnableWithMessageHistory

from helpers.prompts import get_system_prompt
from helpers.llm import get_bedrock_llm
from helpers.vectorstore import get_vectorstore_retriever

logger = logging.getLogger(__name__)

SIMULATED_ROLE = os.getenv("SIMULATED_ROLE", "patient")
PRACTITIONER_ROLE = os.getenv("PRACTITIONER_ROLE", "pharmacist")

# Chain cache keyed by (patient_id, group_prompt) — one chain per patient/group combination.
# Built once at session start (prewarm) and reused for all turns within that session.
_chain_cache: dict = {}
_db_credentials_cache = None


def _get_db_credentials() -> dict:
    global _db_credentials_cache
    if _db_credentials_cache is None:
        secret_name = os.getenv("SM_DB_CREDENTIALS")
        if not secret_name:
            raise RuntimeError("SM_DB_CREDENTIALS env var not set")
        client = boto3.client("secretsmanager")
        response = client.get_secret_value(SecretId=secret_name)
        _db_credentials_cache = json.loads(response["SecretString"])
    return _db_credentials_cache


def _build_chain(
    patient_name: str,
    patient_prompt: str,
    group_prompt: str,
    patient_id: str,
    llm_model_id: str,
    table_name: str,
) -> RunnableWithMessageHistory:
    """
    Build a conversational RAG chain for the given patient.
    Mirrors conversation.py get_response() exactly:
      - system prompt loaded from DB (system_prompt_history), hardcoded fallback
      - group_prompt appended (from simulation_groups.system_prompt via EXTRA_SYSTEM_PROMPT)
      - same LangChain retrieval chain structure
    """
    region = os.getenv("AWS_REGION", "us-east-1")
    embedding_model_id = os.getenv("EMBEDDING_MODEL_ID", "amazon.titan-embed-text-v2:0")
    rds_endpoint = os.getenv("RDS_PROXY_ENDPOINT")

    if not rds_endpoint:
        raise RuntimeError("RDS_PROXY_ENDPOINT env var not set")

    llm = get_bedrock_llm(bedrock_llm_id=llm_model_id, streaming=False)

    bedrock_client = boto3.client("bedrock-runtime", region_name=region)
    embeddings = BedrockEmbeddings(model_id=embedding_model_id, client=bedrock_client)

    secret = _get_db_credentials()
    vectorstore_config_dict = {
        "collection_name": patient_id,
        "dbname": secret["dbname"],
        "user": secret["username"],
        "password": secret["password"],
        "host": rds_endpoint,
        "port": secret["port"],
    }

    history_aware_retriever = get_vectorstore_retriever(
        llm=llm,
        vectorstore_config_dict=vectorstore_config_dict,
        embeddings=embeddings,
    )

    # Load system prompt from DB; fall back to hardcoded default — same as conversation.py
    system_prompt = get_system_prompt(patient_name)

    role = SIMULATED_ROLE
    pro = PRACTITIONER_ROLE
    final_system_prompt = f"""
<|begin_of_text|>
<|start_header_id|>{role}<|end_header_id|>

CRITICAL: You are {patient_name or f'the {role}'}, a {role.upper()} seeking help from a {pro}.
NEVER act as an expert or {pro}. ALWAYS respond as a {role}.

{system_prompt}
{group_prompt or ''}

Additional details about your personality, symptoms or condition:
{patient_prompt if patient_prompt else "No additional details provided."}

<|eot_id|>
<|start_header_id|>documents<|end_header_id|>
{{context}}
<|eot_id|>
"""

    qa_prompt = ChatPromptTemplate.from_messages([
        ("system", final_system_prompt),
        MessagesPlaceholder("chat_history"),
        ("human", "{input}"),
    ])
    question_answer_chain = create_stuff_documents_chain(llm, qa_prompt)
    rag_chain = create_retrieval_chain(history_aware_retriever, question_answer_chain)

    return RunnableWithMessageHistory(
        rag_chain,
        lambda sid: DynamoDBChatMessageHistory(table_name=table_name, session_id=sid),
        input_messages_key="input",
        history_messages_key="chat_history",
        output_messages_key="answer",
    )


def ensure_chain(
    patient_id: str,
    patient_name: str,
    patient_prompt: str,
    group_prompt: str,
    table_name: str,
) -> None:
    """
    Build and cache the LLaMA chain for the given patient/group combination.
    Called from nova_sonic.py via run_in_executor before audio suppression is enabled,
    so a build failure falls back to Nova Sonic's own response rather than silent failure.
    """
    llm_model_id = os.getenv("LLAMA_MODEL_ID", "meta.llama3-70b-instruct-v1:0")
    rds_endpoint = os.getenv("RDS_PROXY_ENDPOINT", "")
    sm_secret = os.getenv("SM_DB_CREDENTIALS", "")
    print(f"🤖 RAG_CHAIN: ensure_chain — patient_id={patient_id!r}, name={patient_name!r}, model={llm_model_id!r}", flush=True)
    print(f"🤖 RAG_CHAIN: env — RDS_PROXY_ENDPOINT={'SET' if rds_endpoint else 'MISSING'}, SM_DB_CREDENTIALS={'SET' if sm_secret else 'MISSING'}", flush=True)
    cache_key = (patient_id or "default", group_prompt or "")
    if cache_key not in _chain_cache:
        logger.info(f"🤖 RAG_CHAIN: Building chain for patient_id={patient_id!r}")
        print(f"🤖 RAG_CHAIN: Building chain for patient_id={patient_id!r}", flush=True)
        _chain_cache[cache_key] = _build_chain(
            patient_name=patient_name,
            patient_prompt=patient_prompt,
            group_prompt=group_prompt,
            patient_id=patient_id,
            llm_model_id=llm_model_id,
            table_name=table_name,
        )
        logger.info(f"🤖 RAG_CHAIN: Chain built for patient_id={patient_id!r}")
        print(f"🤖 RAG_CHAIN: Chain successfully built for patient_id={patient_id!r}", flush=True)
    else:
        print(f"🤖 RAG_CHAIN: Cache hit for patient_id={patient_id!r}", flush=True)


async def call_llama_rag(
    user_text: str,
    session_id: str,
    patient_name: str,
    patient_prompt: str,
    group_prompt: str,
    patient_id: str,
    table_name: str,
) -> str:
    """
    Invoke LLaMA 3 70B + pgvector RAG for the given user utterance.
    Returns the plain-text patient response.
    """
    ensure_chain(patient_id, patient_name, patient_prompt, group_prompt, table_name)
    chain = _chain_cache[(patient_id or "default", group_prompt or "")]

    def _invoke():
        return chain.invoke(
            {"input": user_text},
            config={"configurable": {"session_id": session_id}},
        )["answer"]

    logger.info(f"🤖 RAG_CHAIN: Invoking LLaMA for session={session_id}, input={user_text[:60]}...")
    print(f"🤖 RAG_CHAIN: Invoking LLaMA — session={session_id}, input={user_text[:80]!r}", flush=True)
    loop = asyncio.get_event_loop()
    result = await loop.run_in_executor(None, _invoke)
    logger.info(f"🤖 RAG_CHAIN: Response received: {result[:80]}...")
    print(f"🤖 RAG_CHAIN: LLaMA response ({len(result)} chars): {result[:120]!r}", flush=True)
    return result
